# Generated by Django 4.2.7 on 2023-12-15 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteName', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkPointofReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operator_Name', models.CharField(max_length=200)),
                ('Operator_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedQualityReadability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Readability_no', models.IntegerField()),
                ('Readability_description', models.TextField()),
                ('Readability_meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedQualitySignalStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Signalstrength_no', models.IntegerField()),
                ('Signalstrength_description', models.TextField()),
                ('Signalstrength_meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadioMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Measurement_Date', models.DateField()),
                ('Measurement_Time', models.TimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('Field_Strength_dbuv_m', models.FloatField()),
                ('Signal_Strength_dbm', models.FloatField()),
                ('DSC_Response', models.CharField(blank=True, max_length=100, null=True)),
                ('Tx_site', models.CharField(blank=True, max_length=100, null=True)),
                ('Rx_site', models.CharField(blank=True, max_length=100, null=True)),
                ('ReceivedQuality_Description', models.TextField(blank=True, null=True)),
                ('Readability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_measurements', to='Dashboard.receivedqualityreadability')),
                ('SignalStrength', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_measurements', to='Dashboard.receivedqualitysignalstrength')),
                ('npr_sites', models.ManyToManyField(related_name='radio_measurements', to='Dashboard.networkpointofreception')),
            ],
        ),
        migrations.CreateModel(
            name='CellularMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('RSSI', models.IntegerField()),
                ('RSCP', models.IntegerField()),
                ('Cell_Site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cellular_measurements', to='Dashboard.cellsite')),
            ],
        ),
        migrations.AddField(
            model_name='cellsite',
            name='Network_Technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_site', to='Dashboard.networktechnology'),
        ),
        migrations.AddField(
            model_name='cellsite',
            name='Operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_site', to='Dashboard.operator'),
        ),
    ]
