# Generated by Django 4.2.7 on 2023-12-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiomeasurement',
            name='npr_sites',
        ),
        migrations.AddField(
            model_name='radiomeasurement',
            name='npr_sites',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
